spring:
  application:
    name: rabbitmq-order-consumer
  rabbitmq:
    host: 172.16.30.21
    password: 310012
    username: rabbitmq
    #    ????????????????????????
    template:
      retry:
        enabled: true
        initial-interval: 2s